# Generated by Django 4.1 on 2022-08-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('walk_score_url', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('safety', models.CharField(max_length=100)),
                ('known_for', models.CharField(max_length=100)),
                ('photos', models.CharField(max_length=100)),
            ],
        ),
    ]
