# Generated by Django 4.1 on 2022-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='journal',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
