# Generated by Django 4.1 on 2022-08-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_destination_rename_journal_trip_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['a_date']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='d_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='a_date',
            field=models.DateTimeField(default="2022-01-01", verbose_name='Activity Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='a_time',
            field=models.TimeField(default="00:00", verbose_name='Activity Time'),
            preserve_default=False,
        ),
    ]
