# Generated by Django 4.1 on 2022-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_activity_options_remove_activity_d_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='a_date',
            field=models.DateField(verbose_name='Activity Date'),
        ),
    ]
