# Generated by Django 4.1 on 2022-08-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_activity_a_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='accommodation',
            field=models.CharField(default='None Yet!', max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.CharField(default='None Yet!', max_length=1000),
        ),
    ]
