# Generated by Django 4.1 on 2022-08-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_trip_accommodation_alter_trip_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['a_date', 'a_time']},
        ),
    ]
